### ISSUE TITLE
Font changes when pressing Home from the membership page

### ISSUE THREAD

**Issue by akrakman** [acm-uiuc/acm-uiuc.github.io#30]
<img width="1144" alt="Screen Shot 2022-09-02 at 12 32 14 AM" src="https://user-images.githubusercontent.com/59807670/188065783-a5f6e9fd-d61a-46cc-bb35-dc9f570cdb5d.png">

**Comment by shg8** [comment]
Unfortunately everything is prerendered right now so the font might not have loaded before the page loads. Once we migrate away from GCP and have proper control of url rewrites, we can deal with this issue.

**Comment by akrakman** [comment]
Maybe it should have an <a> tag instead.

**Comment by devksingh4** [comment]
Fix implemented in #50.
